### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by ashenfal** [luminus-framework/guestbook#15]
I've been working through the guestbook application tutorial and got a compiler error. To make sure I'm not just being dumb, I cloned this repo, typed "lein run migrate", and got the same error. Here's the first bit of the stack trace:

> java.lang.ExceptionInInitializerError
>         at clojure.main.<clinit>(main.java:20)
> Caused by: java.lang.RuntimeException: No such var: db/get-messages, compiling:(
> guestbook/routes/home.clj:14:22)
>         at clojure.lang.Compiler.analyze(Compiler.java:6688)

If I switch the order of the queries in queries.sql, it's always the second one that causes the "No such var" issue. It may be relevant that I'm working in Windows.  Do you have any ideas what has gone wrong?

**Comment by yogthos** [comment]
Could be that your lein version is out of date, you can check with `lein version`. The minimum version is `2.5.3`. Another thing to check is you JDK version, it should be at at least `1.7`.

I just tried locally, and I'm unable to replicate the issue:

```
it clone https://github.com/luminus-framework/guestbook.git
Cloning into 'guestbook'...
remote: Counting objects: 568, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 568 (delta 0), reused 0 (delta 0), pack-reused 560
Receiving objects: 100% (568/568), 161.62 KiB | 0 bytes/s, done.
Resolving deltas: 100% (228/228), done.
Checking connectivity... done.
> lein run migrate
No :main namespace specified in project.clj.
> cd guestbook/
guestbook> lein run migrate
[2016-02-23 17:20:50,552][DEBUG][org.jboss.logging] Logging Provider: org.jboss.logging.Log4jLoggerProvider
[2016-02-23 17:20:51,611][INFO][migratus.core] Starting migrations
[2016-02-23 17:20:51,851][INFO][migratus.database] creating migration table 'schema_migrations'
[2016-02-23 17:20:51,874][INFO][migratus.core] Running up for [20160221190951]
[2016-02-23 17:20:51,874][INFO][migratus.core] Up 20160221190951-add-users-table
[2016-02-23 17:20:51,878][DEBUG][migratus.database] found 1 up migrations
[2016-02-23 17:20:51,892][DEBUG][migratus.database] marking 20160221190951 complete
[2016-02-23 17:20:51,901][INFO][migratus.core] Ending migrations
```

**Comment by ashenfal** [comment]
Here are my versions, they should be good:
> C:\Users\ashenfal\luminus\guestbook>lein version
> Leiningen 2.6.1 on Java 1.8.0_31 Java HotSpot(TM) 64-Bit Server VM
> C:\Users\ashenfal\luminus\guestbook>Java -version
> java version "1.8.0_71"
> Java(TM) SE Runtime Environment (build 1.8.0_71-b15)
> Java HotSpot(TM) 64-Bit Server VM (build 25.71-b15, mixed mode)
I'll try running it on a Mac, maybe it's a Windows thing.

**Comment by yogthos** [comment]
Yeah everything looks ok there, I haven't tried running on windows, but I don't see why that should make a difference. The error seems to indicate that [get-messages](https://github.com/luminus-framework/guestbook/blob/0198c702d0c544155527405e9d272983e0d0c9d3/resources/sql/queries.sql#L7) from the SQL file aren't being compiled to a function. This should happen when [conman/bind-connection](https://github.com/luminus-framework/guestbook/blob/0198c702d0c544155527405e9d272983e0d0c9d3/src/clj/guestbook/db/core.clj#L18) is run. That happens at compile time, so those functions should be available when the namespace is loaded.

Only other thing I can think of is checking your `~/.lein/profiles.clj` to see if you have any plugins loaded.

**Comment by ashenfal** [comment]
I just got it running on a different laptop (a Mac), so there's something about my machine that's making trouble. The only plugin I have is cider -nrepl, version 0.8.1. I agree that the trouble is with bind-connection. It's like it only reads the first query in the file for some reason. I'll poke at it a bit and let you know if I figure it out.

**Comment by yogthos** [comment]
interesting, definitely keep me posted on this

**Comment by yogthos** [comment]
I think it might be this issue https://github.com/layerware/hugsql/issues/23 I pushed out an update for conman and luminus using the latest hugsql version

**Comment by ashenfal** [comment]
I cloned a new repo, and I still get the same error. I also think it's a problem with hugsql -- their test for hugsql_core fails to compile on this machine. I'm going to keep working at it.

**Comment by ashenfal** [comment]
Submitted an issue with hugsql. I suspect its something to do with how their parser handles newlines. I'll keep you updated.

**Comment by yogthos** [comment]
great thanks

**Comment by RobSullivan** [comment]
I was having the same no such var issue this evening following the tutorial (on a mac). After updating to conman 0.4.4 the issue was no more.

**Comment by csummers** [comment]
@ashenfal submitted a bug regarding HugSQL parsing of Windows newlines: https://github.com/layerware/hugsql/issues/26

This was fixed in HugSQL 0.4.3

**Comment by yogthos** [comment]
just updated conman to `"0.4.5"` referencing the latest HugSQL, hopefully everything should be in order now

**Comment by ashenfal** [comment]
I updated conman to `"0.4.5"` and it's working! Thank you so much!

**Comment by yogthos** [comment]
fantastic!
